update=6/27/2020 6:37:06 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=digikey-kicad-library;digikey-kicad-library/digikey-symbols;MCU_Texas_MSP430
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=switches
LibName4=relays
LibName5=motors
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=microcontrollers
LibName16=dsp
LibName17=microchip
LibName18=analog_switches
LibName19=motorola
LibName20=texas
LibName21=intel
LibName22=audio
LibName23=interface
LibName24=digital-audio
LibName25=philips
LibName26=display
LibName27=cypress
LibName28=siliconi
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
LibName33=digikey-kicad-library/digikey-symbols/dk_Addressable-Specialty
LibName34=digikey-kicad-library/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName35=digikey-kicad-library/digikey-symbols/dk_Automotive-Relays
LibName36=digikey-kicad-library/digikey-symbols/dk_Balun
LibName37=digikey-kicad-library/digikey-symbols/dk_Banana-and-Tip-Connectors-Jacks-Plugs
LibName38=digikey-kicad-library/digikey-symbols/dk_Barrel-Audio-Connectors
LibName39=digikey-kicad-library/digikey-symbols/dk_Barrel-Power-Connectors
LibName40=digikey-kicad-library/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName41=digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName42=digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName43=digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName44=digikey-kicad-library/digikey-symbols/dk_Coaxial-Connectors-RF
LibName45=digikey-kicad-library/digikey-symbols/dk_Crystals
LibName46=digikey-kicad-library/digikey-symbols/dk_Current-Sensors
LibName47=digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName48=digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName49=digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName50=digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName51=digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName52=digikey-kicad-library/digikey-symbols/dk_DC-DC-Converters
LibName53=digikey-kicad-library/digikey-symbols/dk_Digital-Isolators
LibName54=digikey-kicad-library/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName55=digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName56=digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName57=digikey-kicad-library/digikey-symbols/dk_Diodes-Zener-Single
LibName58=digikey-kicad-library/digikey-symbols/dk_Display-Modules-LCD-OLED-Graphic
LibName59=digikey-kicad-library/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName60=digikey-kicad-library/digikey-symbols/dk_D-Sub-Connectors
LibName61=digikey-kicad-library/digikey-symbols/dk_Embedded-Microcontrollers
LibName62=digikey-kicad-library/digikey-symbols/dk_Encoders
LibName63=digikey-kicad-library/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName64=digikey-kicad-library/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName65=digikey-kicad-library/digikey-symbols/dk_Fixed-Inductors
LibName66=digikey-kicad-library/digikey-symbols/dk_Fuses
LibName67=digikey-kicad-library/digikey-symbols/dk_Gas-Sensors
LibName68=digikey-kicad-library/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName69=digikey-kicad-library/digikey-symbols/dk_Image-Sensors-Camera
LibName70=digikey-kicad-library/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName71=digikey-kicad-library/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName72=digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName73=digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName74=digikey-kicad-library/digikey-symbols/dk_Interface-Controllers
LibName75=digikey-kicad-library/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName76=digikey-kicad-library/digikey-symbols/dk_Interface-I-O-Expanders
LibName77=digikey-kicad-library/digikey-symbols/dk_Interface-Modules
LibName78=digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName79=digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName80=digikey-kicad-library/digikey-symbols/dk_Interface-Specialized
LibName81=digikey-kicad-library/digikey-symbols/dk_LED-Indication-Discrete
LibName82=digikey-kicad-library/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName83=digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName84=digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName85=digikey-kicad-library/digikey-symbols/dk_Linear-Comparators
LibName86=digikey-kicad-library/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName87=digikey-kicad-library/digikey-symbols/dk_Logic-Flip-Flops
LibName88=digikey-kicad-library/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName89=digikey-kicad-library/digikey-symbols/dk_Logic-Multivibrators
LibName90=digikey-kicad-library/digikey-symbols/dk_Logic-Shift-Registers
LibName91=digikey-kicad-library/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName92=digikey-kicad-library/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName93=digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName94=digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName95=digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName96=digikey-kicad-library/digikey-symbols/dk_Memory
LibName97=digikey-kicad-library/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName98=digikey-kicad-library/digikey-symbols/dk_Microphones
LibName99=digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks
LibName100=digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName101=digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName102=digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName103=digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName104=digikey-kicad-library/digikey-symbols/dk_Navigation-Switches-Joystick
LibName105=digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName106=digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Distance-Measuring
LibName107=digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName108=digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName109=digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName110=digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName111=digikey-kicad-library/digikey-symbols/dk_Optoisolators-Logic-Output
LibName112=digikey-kicad-library/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName113=digikey-kicad-library/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName114=digikey-kicad-library/digikey-symbols/dk_Oscillators
LibName115=digikey-kicad-library/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName116=digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Chargers
LibName117=digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Management
LibName118=digikey-kicad-library/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName119=digikey-kicad-library/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName120=digikey-kicad-library/digikey-symbols/dk_PMIC-Gate-Drivers
LibName121=digikey-kicad-library/digikey-symbols/dk_PMIC-LED-Drivers
LibName122=digikey-kicad-library/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName123=digikey-kicad-library/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName124=digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName125=digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName126=digikey-kicad-library/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName127=digikey-kicad-library/digikey-symbols/dk_PMIC-Supervisors
LibName128=digikey-kicad-library/digikey-symbols/dk_PMIC-Thermal-Management
LibName129=digikey-kicad-library/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName130=digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Reference
LibName131=digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName132=digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName133=digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName134=digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName135=digikey-kicad-library/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName136=digikey-kicad-library/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName137=digikey-kicad-library/digikey-symbols/dk_Pushbutton-Switches
LibName138=digikey-kicad-library/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName139=digikey-kicad-library/digikey-symbols/dk_Reed-Relays
LibName140=digikey-kicad-library/digikey-symbols/dk_Resistor-Networks-Arrays
LibName141=digikey-kicad-library/digikey-symbols/dk_RF-Amplifiers
LibName142=digikey-kicad-library/digikey-symbols/dk_RF-Antennas
LibName143=digikey-kicad-library/digikey-symbols/dk_RF-Demodulators
LibName144=digikey-kicad-library/digikey-symbols/dk_RF-Detectors
LibName145=digikey-kicad-library/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName146=digikey-kicad-library/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName147=digikey-kicad-library/digikey-symbols/dk_RF-Receivers
LibName148=digikey-kicad-library/digikey-symbols/dk_RF-Switches
LibName149=digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-ICs
LibName150=digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-Modules
LibName151=digikey-kicad-library/digikey-symbols/dk_RF-Transmitters
LibName152=digikey-kicad-library/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName153=digikey-kicad-library/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName154=digikey-kicad-library/digikey-symbols/dk_Shunts-Jumpers
LibName155=digikey-kicad-library/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName156=digikey-kicad-library/digikey-symbols/dk_Slide-Switches
LibName157=digikey-kicad-library/digikey-symbols/dk_Sockets-for-ICs-Transistors
LibName158=digikey-kicad-library/digikey-symbols/dk_Solid-State-Relays
LibName159=digikey-kicad-library/digikey-symbols/dk_Specialized-ICs
LibName160=digikey-kicad-library/digikey-symbols/dk_Specialized-Sensors
LibName161=digikey-kicad-library/digikey-symbols/dk_Surge-Suppression-ICs
LibName162=digikey-kicad-library/digikey-symbols/dk_Tactile-Switches
LibName163=digikey-kicad-library/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName164=digikey-kicad-library/digikey-symbols/dk_Terminal-Blocks-Wire-to-Board
LibName165=digikey-kicad-library/digikey-symbols/dk_Test-Points
LibName166=digikey-kicad-library/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName167=digikey-kicad-library/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName168=digikey-kicad-library/digikey-symbols/dk_Thyristors-SCRs
LibName169=digikey-kicad-library/digikey-symbols/dk_Thyristors-TRIACs
LibName170=digikey-kicad-library/digikey-symbols/dk_Toggle-Switches
LibName171=digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName172=digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName173=digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName174=digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName175=digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName176=digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName177=digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName178=digikey-kicad-library/digikey-symbols/dk_Transistors-JFETs
LibName179=digikey-kicad-library/digikey-symbols/dk_Trimmer-Potentiometers
LibName180=digikey-kicad-library/digikey-symbols/dk_TVS-Diodes
LibName181=digikey-kicad-library/digikey-symbols/dk_TVS-Mixed-Technology
LibName182=digikey-kicad-library/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName183=MCU_Texas_MSP430/MCU_Texas_MSP430
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=./
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceAjustPassiveValues=0
LabSize=50
ERC_TestSimilarLabels=1
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=e-cribbage.net
CopperLayerCount=2
BoardThickness=1.6
AllowMicroVias=0
AllowBlindVias=0
RequireCourtyardDefinitions=0
ProhibitOverlappingCourtyards=1
MinTrackWidth=0.2
MinViaDiameter=0.4
MinViaDrill=0.3
MinMicroViaDiameter=0.2
MinMicroViaDrill=0.09999999999999999
MinHoleToHole=0.25
TrackWidth1=0.25
ViaDiameter1=0.8
ViaDrill1=0.4
dPairWidth1=0.2
dPairGap1=0.25
dPairViaGap1=0.25
SilkLineWidth=0.12
SilkTextSizeV=1
SilkTextSizeH=1
SilkTextSizeThickness=0.15
SilkTextItalic=0
SilkTextUpright=1
CopperLineWidth=0.2
CopperTextSizeV=1.5
CopperTextSizeH=1.5
CopperTextThickness=0.3
CopperTextItalic=0
CopperTextUpright=1
EdgeCutLineWidth=0.05
CourtyardLineWidth=0.05
OthersLineWidth=0.15
OthersTextSizeV=1
OthersTextSizeH=1
OthersTextSizeThickness=0.15
OthersTextItalic=0
OthersTextUpright=1
SolderMaskClearance=0.05
SolderMaskMinWidth=0
SolderPasteClearance=0
SolderPasteRatio=0
[pcbnew/Layer.F.Cu]
Name=F.Cu
Type=0
Enabled=1
[pcbnew/Layer.In1.Cu]
Name=In1.Cu
Type=0
Enabled=0
[pcbnew/Layer.In2.Cu]
Name=In2.Cu
Type=0
Enabled=0
[pcbnew/Layer.In3.Cu]
Name=In3.Cu
Type=0
Enabled=0
[pcbnew/Layer.In4.Cu]
Name=In4.Cu
Type=0
Enabled=0
[pcbnew/Layer.In5.Cu]
Name=In5.Cu
Type=0
Enabled=0
[pcbnew/Layer.In6.Cu]
Name=In6.Cu
Type=0
Enabled=0
[pcbnew/Layer.In7.Cu]
Name=In7.Cu
Type=0
Enabled=0
[pcbnew/Layer.In8.Cu]
Name=In8.Cu
Type=0
Enabled=0
[pcbnew/Layer.In9.Cu]
Name=In9.Cu
Type=0
Enabled=0
[pcbnew/Layer.In10.Cu]
Name=In10.Cu
Type=0
Enabled=0
[pcbnew/Layer.In11.Cu]
Name=In11.Cu
Type=0
Enabled=0
[pcbnew/Layer.In12.Cu]
Name=In12.Cu
Type=0
Enabled=0
[pcbnew/Layer.In13.Cu]
Name=In13.Cu
Type=0
Enabled=0
[pcbnew/Layer.In14.Cu]
Name=In14.Cu
Type=0
Enabled=0
[pcbnew/Layer.In15.Cu]
Name=In15.Cu
Type=0
Enabled=0
[pcbnew/Layer.In16.Cu]
Name=In16.Cu
Type=0
Enabled=0
[pcbnew/Layer.In17.Cu]
Name=In17.Cu
Type=0
Enabled=0
[pcbnew/Layer.In18.Cu]
Name=In18.Cu
Type=0
Enabled=0
[pcbnew/Layer.In19.Cu]
Name=In19.Cu
Type=0
Enabled=0
[pcbnew/Layer.In20.Cu]
Name=In20.Cu
Type=0
Enabled=0
[pcbnew/Layer.In21.Cu]
Name=In21.Cu
Type=0
Enabled=0
[pcbnew/Layer.In22.Cu]
Name=In22.Cu
Type=0
Enabled=0
[pcbnew/Layer.In23.Cu]
Name=In23.Cu
Type=0
Enabled=0
[pcbnew/Layer.In24.Cu]
Name=In24.Cu
Type=0
Enabled=0
[pcbnew/Layer.In25.Cu]
Name=In25.Cu
Type=0
Enabled=0
[pcbnew/Layer.In26.Cu]
Name=In26.Cu
Type=0
Enabled=0
[pcbnew/Layer.In27.Cu]
Name=In27.Cu
Type=0
Enabled=0
[pcbnew/Layer.In28.Cu]
Name=In28.Cu
Type=0
Enabled=0
[pcbnew/Layer.In29.Cu]
Name=In29.Cu
Type=0
Enabled=0
[pcbnew/Layer.In30.Cu]
Name=In30.Cu
Type=0
Enabled=0
[pcbnew/Layer.B.Cu]
Name=B.Cu
Type=0
Enabled=1
[pcbnew/Layer.B.Adhes]
Enabled=1
[pcbnew/Layer.F.Adhes]
Enabled=1
[pcbnew/Layer.B.Paste]
Enabled=1
[pcbnew/Layer.F.Paste]
Enabled=1
[pcbnew/Layer.B.SilkS]
Enabled=1
[pcbnew/Layer.F.SilkS]
Enabled=1
[pcbnew/Layer.B.Mask]
Enabled=1
[pcbnew/Layer.F.Mask]
Enabled=1
[pcbnew/Layer.Dwgs.User]
Enabled=1
[pcbnew/Layer.Cmts.User]
Enabled=1
[pcbnew/Layer.Eco1.User]
Enabled=1
[pcbnew/Layer.Eco2.User]
Enabled=1
[pcbnew/Layer.Edge.Cuts]
Enabled=1
[pcbnew/Layer.Margin]
Enabled=1
[pcbnew/Layer.B.CrtYd]
Enabled=1
[pcbnew/Layer.F.CrtYd]
Enabled=1
[pcbnew/Layer.B.Fab]
Enabled=1
[pcbnew/Layer.F.Fab]
Enabled=1
[pcbnew/Layer.Rescue]
Enabled=1
[pcbnew/Netclasses]
[pcbnew/Netclasses/Default]
Name=Default
Clearance=0.2
TrackWidth=0.25
ViaDiameter=0.8
ViaDrill=0.4
uViaDiameter=0.3
uViaDrill=0.1
dPairWidth=0.2
dPairGap=0.25
dPairViaGap=0.25
